export const config = {
    SERVER_BASE: "http://localhost:5000",
    EVENT_USER_ROLE: ['Admin', 'Guest'],
    ASSOCIATION_USER_ROLE: ['Admin', 'Guest'],
    PUBLIC_EVENT_TAB: ['detail', 'comment'],
    ADMIN_EVENT_TAB: ['detail', 'participant', 'survey', 'comment'],
    PROFILE_TAB: ['upcomming', 'past', 'my_association', 'statistic'],
    ASSOCIATION_TAB: ['event', 'about', 'member'],
    APPLICATION_USER_STATUS: ["Participant", "Vistor", "Guest"],
    EVENT_CATEGORY: {
        career: "Career",
        charities: "Charities",
        fashion: "Fashion",
        festival: "Festival & Fairs",
        film: "Film",
        food: "Food & Drink",
        book: "Lectures & Books",
        music: "Music",
        performing_art: "Performing Arts",
        religion: "Religion",
        sport: "Sport",
        visual_art: "Visual Arts",
        other: "Others",
    },
    EVENT_FORM: {
        carnival: "Carnival",
        class: "Class",
        competition: "Competition",
        exhibition: "Exhibition",
        experience: "Experience",
        party: "Party",
        seminar: "Seminar",
        show: "Show",
        trip: "Trip",
        workshop: "Workshop",
    },
    ASSOCIATION_TYPE: {
        college: "College",
        department: "Department",
        faculty: "Faculty",
        society: "Society",

    },
    TICKET_STATUS_AVALIABLE: 0,
    TICKET_STATUS_USED: 1,
    TICKET_STATUS_PASSED: -1,
}